from __future__ import annotations

from datetime import datetime

import markdown2

from app.config.settings import Settings, get_settings


class NewsletterRenderer:
    def __init__(self, settings: Settings | None = None) -> None:
        self.settings = settings or get_settings()

    def render_html(self, markdown_content: str, subject: str) -> str:
        # We render markdown first so the LLM can produce a readable newsletter
        # without needing to output raw HTML directly.
        html_content = (
            markdown2.markdown(
                markdown_content,
                extras=["tables", "fenced-code-blocks", "break-on-newline"],
            )
            if markdown_content.strip()
            else "<p>No content available</p>"
        )

        return f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{subject}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #f3f6fb; padding: 20px; }}
        .container {{ max-width: 720px; margin: 0 auto; background: #ffffff; border-radius: 18px; overflow: hidden; box-shadow: 0 16px 36px rgba(17, 24, 39, 0.12); }}
        .header {{ background: linear-gradient(135deg, #0f172a 0%, #1d4ed8 100%); color: white; padding: 36px 28px; }}
        .header h1 {{ font-size: 28px; margin-bottom: 8px; }}
        .header p {{ opacity: 0.88; }}
        .content {{ padding: 32px 28px; }}
        .content h1, .content h2 {{ color: #0f172a; margin: 24px 0 14px; }}
        .content h3 {{ color: #1e293b; margin: 18px 0 10px; }}
        .content p, .content li {{ color: #334155; line-height: 1.7; font-size: 16px; }}
        .content ul {{ padding-left: 20px; margin: 14px 0; }}
        .content a {{ color: #2563eb; text-decoration: none; }}
        .footer {{ background: #e2e8f0; color: #334155; padding: 20px 28px; font-size: 14px; }}
        @media (max-width: 640px) {{
            .header, .content, .footer {{ padding: 22px 18px; }}
            .header h1 {{ font-size: 24px; }}
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>{self.settings.newsletter_title}</h1>
            <p>{datetime.now().strftime('%B %d, %Y')}</p>
        </div>
        <div class="content">
            {html_content}
        </div>
        <div class="footer">
            Generated by tech-watch-agent on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
        </div>
    </div>
</body>
</html>
""".strip()

    @staticmethod
    def render_text(markdown_content: str) -> str:
        return markdown_content.replace("**", "").replace("#", "").strip()
